### ISSUE TITLE
Plug-in Extras：An internal error has occurred：bad argument #1 to '?' (String expected, got nil)

### ISSUE THREAD

**Issue by josephtina** [jarnoh/knobroom#25]
When I press start knobroom in "plug-in extras". It shows "An internal error has occurred：bad argument #1 to '?' (String expected, got nil)". Can somebody tell me why?? > <. Now it won't work with my Novation Nocturn...

Thanks

**Comment by mstefanko** [comment]
Getting the same with lightroom 4.2 with korg nanokontrol

**Comment by mpan66** [comment]
Same error exactly using Lightroom 4.4 (haven't tried with an earlier version). I see this with or without a MIDI device connected. Any ideas?

**Comment by HDYA** [comment]
Might related to the different format of shell script between Windows and Mac OS? 
Also, directly execute the command contained in the script still encounter an error, which may also come from similar difference.

```
PS D:\Adobe\Adobe Lightroom\Knobroom.lrplugin\server> node .\Knobroom.js
D:\Adobe\Adobe Lightroom\Knobroom.lrplugin\server\node_modules\bindings\bindings.js:79
        throw e
              ^
Error: %1 is not a valid Win32 application.
D:\Adobe\Adobe Lightroom\Knobroom.lrplugin\server\node_modules\midi\build\Release\midi.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (D:\Adobe\Adobe Lightroom\Knobroom.lrplugin\server\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (D:\Adobe\Adobe Lightroom\Knobroom.lrplugin\server\node_modules\midi\midi.js:1:93)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by jarnoh** [comment]
Windows is not supported.

Knobroom uses undocumented Lightroom API which has different implementation on Windows.  I should rewrite that piece of code with LR6's LrSocket API, but I haven't had the time yet.

**Comment by HDYA** [comment]
Sorry for not noticing the compability. OTL 
Thanks anyway.
It's a genius idea, and ahead of the product [PaletteGear](http://palettegear.com/) more than four years.
